# consumo.py - Lógica de base de datos Oracle con Wallet (mTLS)
import oracledb  # <--- SE LLAMA 'oracledb'
import os
import random
from datetime import datetime

# ==================================
# CONFIGURACIÓN DE LA BASE DE DATOS ORACLE
# ==================================

# Leemos las credenciales desde las Variables de Entorno de Render
DB_USER = os.environ.get("DB_USER")
DB_PASS = os.environ.get("DB_PASS")
DB_DSN = os.environ.get("DB_DSN")         # Esto ahora será 'housesavingdb_low'

# TNS_ADMIN es seteado por el Dockerfile, oracledb lo lee solo.


def init_db():
    """Inicializa la conexión y crea la tabla si no existe."""
    try:
        # Conectamos SIN wallet_password
        # ¡¡¡ERA 'oracledb', NO 'oracledd'!!! (Error mío)
        with oracledb.connect(user=DB_USER, password=DB_PASS, dsn=DB_DSN) as conexion:
            with conexion.cursor() as cursor:
                # Usamos TIMESTAMP y NUMBER, tipos de datos de Oracle
                cursor.execute("""
                BEGIN
                    EXECUTE IMMEDIATE '
                    CREATE TABLE consumo_energia (
                        id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                        fecha_hora TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                        kwh NUMBER(10, 8) NOT NULL,
                        PRIMARY KEY (id)
                    )
                    ';
                EXCEPTION
                    WHEN OTHERS THEN
                        IF SQLCODE = -955 THEN
                            NULL; -- La tabla ya existe, no hacer nada
                        ELSE
                            RAISE;
                        END IF;
                END;
                """)
                print("Tabla 'consumo_energia' verificada/creada en Oracle.")
    except Exception as e:
        print(f"Error al inicializar la base de datos Oracle: {e}")
        # Si la app no puede conectar a la DB, no debe continuar.
        raise


def generar_consumo_energia():
    """Genera un valor aleatorio de consumo de energía (0.05 a 2.5 kWh)."""
    return float(random.uniform(0.05, 2.5))


def guardar_consumo_energia(kwh: float):
    """Guarda un nuevo registro de consumo de energía en Oracle."""
    try:
        # Conectamos SIN wallet_password
        with oracledb.connect(user=DB_USER, password=DB_PASS, dsn=DB_DSN) as conexion:
            with conexion.cursor() as cursor:
                fecha_hora = datetime.now()
                # Usamos :1, :2 como placeholders para los valores
                cursor.execute("INSERT INTO consumo_energia (fecha_hora, kwh) VALUES (:1, :2)", (fecha_hora, kwh))
                conexion.commit()
    except Exception as e:
        print(f"Error al guardar en Oracle: {e}")


def obtener_datos_recientes():
    """Obtiene los 5 registros más recientes de energía desde Oracle."""
    datos_energia = []
    try:
        # Conectamos SIN wallet_password
        with oracledb.connect(user=DB_USER, password=DB_PASS, dsn=DB_DSN) as conexion:
            with conexion.cursor() as cursor:
                # La sintaxis de Oracle para "LIMIT" es "FETCH FIRST..."
                cursor.execute("""
                    SELECT fecha_hora, kwh 
                    FROM consumo_energia 
                    ORDER BY fecha_hora DESC 
                    FETCH FIRST 5 ROWS ONLY
                """)
                for row in cursor:
                    datos_energia.append({"fecha": row[0].strftime("%Y-%m-%d %H:%M:%S"), "kwh": row[1]})
    except Exception as e:
        print(f"Error al obtener datos de Oracle: {e}")

    return {"energia": datos_energia}